### ISSUE TITLE
workflow stopped working

### ISSUE THREAD

**Issue by atanasj** [vinkla/alfred-kaomoji#3]
Hi. 
First off, this is a great workflow that I really like using. However, it seems to have stopped working. I have debugged in `Alfred` with the following output: 

```
[22:35:24.980] Kaomoji[Script Filter] Queuing argument 't'
[22:35:25.058] Kaomoji[Script Filter] Queuing argument 'th'
[22:35:25.107] Kaomoji[Script Filter] Queuing argument 'thi'
[22:35:25.266] Kaomoji[Script Filter] Queuing argument 'this'
[22:35:25.346] Kaomoji[Script Filter] Queuing argument 'this '
[22:35:25.498] Kaomoji[Script Filter] Queuing argument 'this a'
[22:35:25.643] Kaomoji[Script Filter] Queuing argument 'this an'
[22:35:25.772] Kaomoji[Script Filter] Queuing argument 'this and'
[22:35:27.011] Kaomoji[Script Filter] Script with argv 'this and' finished
[22:35:27.014] ERROR: Kaomoji[Script Filter] Code 1: {
	"items": [
		{
			"title": "(node:35351) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\n",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\n(node:35351) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\n```\n\n-\nKaomoji 1.3.0\nAlfred 4.0.3\ndarwin x64 18.6.0",
				"largetype": "(node:35351) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
{
	"items": [
		{
			"title": "RequestError: certificate has expired\n    at ClientRequest.<anonymous> (/Users/atanas/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-kaomoji/node_modules/got/index.js:182:22)\n    at Object.onceWrapper (events.js:291:20)\n    at ClientRequest.emit (events.js:203:13)\n    at TLSSocket.socketErrorListener (_http_client.js:402:9)\n    at TLSSocket.emit (events.js:203:13)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nRequestError: certificate has expired\n    at ClientRequest.<anonymous> (/Users/atanas/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-kaomoji/node_modules/got/index.js:182:22)\n```\n\n-\nKaomoji 1.3.0\nAlfred 4.0.3\ndarwin x64 18.6.0",
				"largetype": "RequestError: certificate has expired\n    at ClientRequest.<anonymous> (/Users/atanas/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-kaomoji/node_modules/got/index.js:182:22)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
[22:35:27.019] ERROR: Kaomoji[Script Filter] JSON error: Garbage at end. in JSON:
{
	"items": [
		{
			"title": "(node:35351) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\n",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\n(node:35351) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\n```\n\n-\nKaomoji 1.3.0\nAlfred 4.0.3\ndarwin x64 18.6.0",
				"largetype": "(node:35351) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
{
	"items": [
		{
			"title": "RequestError: certificate has expired\n    at ClientRequest.<anonymous> (/Users/atanas/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-kaomoji/node_modules/got/index.js:182:22)\n    at Object.onceWrapper (events.js:291:20)\n    at ClientRequest.emit (events.js:203:13)\n    at TLSSocket.socketErrorListener (_http_client.js:402:9)\n    at TLSSocket.emit (events.js:203:13)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nRequestError: certificate has expired\n    at ClientRequest.<anonymous> (/Users/atanas/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-kaomoji/node_modules/got/index.js:182:22)\n```\n\n-\nKaomoji 1.3.0\nAlfred 4.0.3\ndarwin x64 18.6.0",
				"largetype": "RequestError: certificate has expired\n    at ClientRequest.<anonymous> (/Users/atanas/.nvm/versions/node/v12.4.0/lib/node_modules/alfred-kaomoji/node_modules/got/index.js:182:22)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
```

Any idea what is going on here? Is it something on my end?

**Comment by vinkla** [comment]
Are you using Alfred 4? If yes, that’s probably the issue. This workflow doesn’t currently work with Alfred 4.

**Comment by vinkla** [comment]
There seems to be issues with the API's SSL certificates. Will hopefully be fixed soon.
